### ISSUE TITLE
TFT in SPI mode

### ISSUE THREAD

**Issue by jam-sys** [Stutchbury/Manualmatic-Pendant#1]
First of all: Thanks for your excellent project.

I have a question.
In your schematic, you connect IM1, IM2 and IM3 pins to GND.
The Adafruit documentation recommend to tie these pins to 3.3 Volts.
What is the proper way?

**Comment by Stutchbury** [comment]
> First of all: Thanks for your excellent project.

Thank you.

> 
> I have a question. In your schematic, you connect IM1, IM2 and IM3 pins to GND. The Adafruit documentation recommend to tie these pins to 3.3 Volts. What is the proper way?

It took me a little while to work this one out as I'd not knowingly referenced IM1-3! 

In the schematic, pins 15-18 on J1 are actually connections to the corner pads of the display/PCB for a modified symbol (and footprint) that provides pads only for the connections required by the Manualmatic. If I'd used the Adafruit footprint, it would have placed down both sides leaving no room for buttons.

The IM1, IM2 and IM3 SPI Mode Jumpers (on the back of the display) are closed with solder as per the Adafruit instructions here: https://learn.adafruit.com/adafruit-2-8-and-3-2-color-tft-touchscreen-breakout-v2/spi-wiring-and-test#spi-mode-jumpers-906160-5

I have updated the schematic with a comment which will hopefully help.
