### ISSUE TITLE
Option to compile for STM32?

### ISSUE THREAD

**Issue by TadyTheFish** [Stutchbury/Manualmatic-Pendant#2]
Hello!
Love the project you have made and I would like to make it for my machine, but I would like to know if it is possible to compile it for a STM32F1 or F4 MCU? I have a bunch laying around and no Teensy and they are not really so cheap as STMs
I tried to compile for STM but it seems that the min, max and round macros are not defined in STM32 core .. Go figure. And the compiler throws a lot of errors ManualmaticControl.cpp and ManualMAticDisplay.cpp, Something about no suitable conversion function from "lambda [] 
Maybe it is because a different compiler is used for the STM32. I know how to code stuff but lambdas are out of my scope :)
Thank you

**Comment by Stutchbury** [comment]
Hi Tady - the Manualmatic is kinda designed around the Teensy 4.1 - primarily for the number of pins, speed of processor and PJRC's interrupt driven encoder library. I have never compiled any code for STM32, so unfortunately am not best placed to advise you. I suspect the missing macros and lambdas are part of the included Arduino or Teensy libraries?

**Comment by TadyTheFish** [comment]
Yeah PJRC's enoder library is portes for more platforms. Those missing macros are a strange thing if you ask me min, max andround should be a part of the core...
The biggest problem for me is those lambda errors.
Whell no problem thank you for your time and this great project. I will mark this as closed 😁
