### ISSUE TITLE
PCB schematic

### ISSUE THREAD

**Issue by ulope** [Stutchbury/Manualmatic-Pendant#5]
Our makerspace is just building its MPCNC and I discovered this project - really awesome, thanks for making it open!

I was wondering if you plan to release the PCB schematic (and ideally, component bom, production files, etc.) as well?

**Comment by Stutchbury** [comment]
Hi Ulrich
It was always the plan to release the PCB files but I wanted to get it into the hands of other people before I did. And now I've updated laptop/KiCAD which has slightly broken my design (I had custom footprints that haven't quite come across properly).
In the meantime, I have a few spare PCBs and thank to Mouser minimum order value) usually a few of the components - my email is in my github profile.
